services:
  - type: web
    name: confession-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    environment:
      pythonVersion: 3.11.9
